spring:
  application:
    name: eureka

server:
  shutdown: graceful # 서버 종료 방식 설정
  port: 8761

eureka:
  server:
    enable-self-preservation: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  config:
    activate:
      on-profile: dev

server:
  port: 8762

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/