spring:
  profiles:
    active: default

  application:
    name: eureka

  config:
    import: optional:configserver:http://localhost:9000

  cloud:
    config:
      label: main

eureka:
  user:
    name: admin
    password: 1234 # 나중에 config server를 통해 주입될 예정

  client:
    register-with-eureka: false
    fetch-registry: false

---
spring:
  config:
    activate:
      on-profile: live

    import: optional:configserver:http://55g-config-live:9000

---
spring:
  config:
    activate:
      on-profile: dev

    import: optional:configserver:http://55g-config-dev:9050
---
spring:
  config:
    activate:
      on-profile: local-docker

    import: optional:configserver:http://host.docker.internal:9000
