spring:
  application:
    name: eureka

server:
  shutdown: graceful # 서버 종료 방식 설정
  port: 8761

eureka:
  server:
    enable-self-preservation: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/

55g:
  log:
    path: .

---
spring:
  config:
    activate:
      on-profile: live

logging:
  file:
    name: ${55g.log.path}/eureka-live.log
  logback:
    rollingpolicy:
      max-history: 100
      file-name-pattern: ${55g.log.path}/eureka-live-%d{yyyy-MM-dd_HH:mm}.%i.log
      max-file-size: 100KB
  level:
    root: info
    shop.S5G.shop: info
55g:
  log:
    path: /logs/live/eureka
---
spring:
  config:
    activate:
      on-profile: dev

server:
  port: 8762

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
logging:
  file:
    name: ${55g.log.path}/eureka-dev.log
  logback:
    rollingpolicy:
      max-history: 10
      file-name-pattern: ${55g.log.path}/eureka-dev-%d{yyyy-MM-dd}.%i.log
      max-file-size: 100KB
  level:
    root: debug
    shop.S5G.shop: trace

55g:
  log:
    path: /logs/dev/eureka